/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jvm_FrameTest */

#ifndef _Included_jvm_FrameTest
#define _Included_jvm_FrameTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jvm_FrameTest
 * Method:    nativeCall
 * Signature: (IIIIIIII)I
 */
JNIEXPORT jint JNICALL Java_jvm_FrameTest_nativeCall
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
