
package client.com.myws;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "annotation_test", targetNamespace = "http://www.myws.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AnnotationTest {


    /**
     * 
     * @param customer
     * @return
     *     returns javax.xml.ws.Response<client.com.myws.NameResponse>
     */
    @WebMethod(operationName = "name")
    @RequestWrapper(localName = "name", targetNamespace = "http://www.myws.com", className = "client.com.myws.Name")
    @ResponseWrapper(localName = "nameResponse", targetNamespace = "http://www.myws.com", className = "client.com.myws.NameResponse")
    public Response<NameResponse> nameAsync(
        @WebParam(name = "customer", targetNamespace = "")
        String customer);

    /**
     * 
     * @param asyncHandler
     * @param customer
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "name")
    @RequestWrapper(localName = "name", targetNamespace = "http://www.myws.com", className = "client.com.myws.Name")
    @ResponseWrapper(localName = "nameResponse", targetNamespace = "http://www.myws.com", className = "client.com.myws.NameResponse")
    public Future<?> nameAsync(
        @WebParam(name = "customer", targetNamespace = "")
        String customer,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<NameResponse> asyncHandler);

    /**
     * 
     * @param customer
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "outcome", targetNamespace = "")
    @RequestWrapper(localName = "name", targetNamespace = "http://www.myws.com", className = "client.com.myws.Name")
    @ResponseWrapper(localName = "nameResponse", targetNamespace = "http://www.myws.com", className = "client.com.myws.NameResponse")
    @Action(input = "http://www.myws.com/annotation_test/nameRequest", output = "http://www.myws.com/annotation_test/nameResponse")
    public String name(
        @WebParam(name = "customer", targetNamespace = "")
        String customer);

}
