
package client.com.myws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "showPeople", targetNamespace = "http://myws.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ShowPeople {


    /**
     * 
     * @return
     *     returns java.util.List<client.com.myws.Person>
     */
    @WebMethod
    @WebResult(name = "people", targetNamespace = "")
    @RequestWrapper(localName = "show", targetNamespace = "http://myws.com/", className = "client.com.myws.Show")
    @ResponseWrapper(localName = "showResponse", targetNamespace = "http://myws.com/", className = "client.com.myws.ShowResponse")
    @Action(input = "http://myws.com/showPeople/showRequest", output = "http://myws.com/showPeople/showResponse")
    public List<Person> show();

}
