
package client.com.myws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ShowPeopleServiceService", targetNamespace = "http://myws.com/", wsdlLocation = "http://192.168.1.100:8080/spring_jaxws/people?wsdl")
public class ShowPeopleServiceService
    extends Service
{

    private final static URL SHOWPEOPLESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SHOWPEOPLESERVICESERVICE_EXCEPTION;
    private final static QName SHOWPEOPLESERVICESERVICE_QNAME = new QName("http://myws.com/", "ShowPeopleServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.100:8080/spring_jaxws/people?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SHOWPEOPLESERVICESERVICE_WSDL_LOCATION = url;
        SHOWPEOPLESERVICESERVICE_EXCEPTION = e;
    }

    public ShowPeopleServiceService() {
        super(__getWsdlLocation(), SHOWPEOPLESERVICESERVICE_QNAME);
    }

    public ShowPeopleServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SHOWPEOPLESERVICESERVICE_QNAME, features);
    }

    public ShowPeopleServiceService(URL wsdlLocation) {
        super(wsdlLocation, SHOWPEOPLESERVICESERVICE_QNAME);
    }

    public ShowPeopleServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SHOWPEOPLESERVICESERVICE_QNAME, features);
    }

    public ShowPeopleServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShowPeopleServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ShowPeople
     */
    @WebEndpoint(name = "showPeoplePort")
    public ShowPeople getShowPeoplePort() {
        return super.getPort(new QName("http://myws.com/", "showPeoplePort"), ShowPeople.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ShowPeople
     */
    @WebEndpoint(name = "showPeoplePort")
    public ShowPeople getShowPeoplePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://myws.com/", "showPeoplePort"), ShowPeople.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SHOWPEOPLESERVICESERVICE_EXCEPTION!= null) {
            throw SHOWPEOPLESERVICESERVICE_EXCEPTION;
        }
        return SHOWPEOPLESERVICESERVICE_WSDL_LOCATION;
    }

}
