
package client.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "webservicecontextService", targetNamespace = "http://webservice/", wsdlLocation = "http://192.168.100.104:8080/spring_jaxws/clientIP?wsdl")
public class WebservicecontextService
    extends Service
{

    private final static URL WEBSERVICECONTEXTSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICECONTEXTSERVICE_EXCEPTION;
    private final static QName WEBSERVICECONTEXTSERVICE_QNAME = new QName("http://webservice/", "webservicecontextService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.100.104:8080/spring_jaxws/clientIP?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICECONTEXTSERVICE_WSDL_LOCATION = url;
        WEBSERVICECONTEXTSERVICE_EXCEPTION = e;
    }

    public WebservicecontextService() {
        super(__getWsdlLocation(), WEBSERVICECONTEXTSERVICE_QNAME);
    }

    public WebservicecontextService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICECONTEXTSERVICE_QNAME, features);
    }

    public WebservicecontextService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICECONTEXTSERVICE_QNAME);
    }

    public WebservicecontextService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICECONTEXTSERVICE_QNAME, features);
    }

    public WebservicecontextService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebservicecontextService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Webservicecontext
     */
    @WebEndpoint(name = "webservicecontextPort")
    public Webservicecontext getWebservicecontextPort() {
        return super.getPort(new QName("http://webservice/", "webservicecontextPort"), Webservicecontext.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Webservicecontext
     */
    @WebEndpoint(name = "webservicecontextPort")
    public Webservicecontext getWebservicecontextPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice/", "webservicecontextPort"), Webservicecontext.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICECONTEXTSERVICE_EXCEPTION!= null) {
            throw WEBSERVICECONTEXTSERVICE_EXCEPTION;
        }
        return WEBSERVICECONTEXTSERVICE_WSDL_LOCATION;
    }

}
