
package client.webservice;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "webservicecontext", targetNamespace = "http://webservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Webservicecontext {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "clientIP", targetNamespace = "http://webservice/", className = "client.webservice.ClientIP")
    @ResponseWrapper(localName = "clientIPResponse", targetNamespace = "http://webservice/", className = "client.webservice.ClientIPResponse")
    @Action(input = "http://webservice/webservicecontext/clientIPRequest", output = "http://webservice/webservicecontext/clientIPResponse")
    public String clientIP();

}
