//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.22 at 11:26:36 ÉÏÎç CST 
//


package step4;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the step4 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BackSides_QNAME = new QName("http://www.mytest2.com", "back-sides");
    private final static QName _Model_QNAME = new QName("http://www.mytest2.com", "model");
    private final static QName _Notes_QNAME = new QName("http://www.mytest2.com", "notes");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: step4
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Pianos }
     * 
     */
    public Pianos createPianos() {
        return new Pianos();
    }

    /**
     * Create an instance of {@link Builder }
     * 
     */
    public Builder createBuilder() {
        return new Builder();
    }

    /**
     * Create an instance of {@link Top }
     * 
     */
    public Top createTop() {
        return new Top();
    }

    /**
     * Create an instance of {@link Piano }
     * 
     */
    public Piano createPiano() {
        return new Piano();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mytest2.com", name = "back-sides")
    public JAXBElement<String> createBackSides(String value) {
        return new JAXBElement<String>(_BackSides_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mytest2.com", name = "model")
    public JAXBElement<String> createModel(String value) {
        return new JAXBElement<String>(_Model_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mytest2.com", name = "notes")
    public JAXBElement<String> createNotes(String value) {
        return new JAXBElement<String>(_Notes_QNAME, String.class, null, value);
    }

}
