//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.22 at 11:26:36 ионГ CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.mytest2.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package step4;
