//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.22 at 11:26:36 ÉÏÎç CST 
//


package step4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import step3.NoteTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.mytest2.com}builder"/>
 *         &lt;element ref="{http://www.mytest2.com}model"/>
 *         &lt;element ref="{http://www.mytest2.com}back-sides"/>
 *         &lt;element ref="{http://www.mytest2.com}top"/>
 *         &lt;element ref="{http://www.mytest2.com}notes" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "builder",
    "model",
    "backSides",
    "top",
    "notes"
})
@XmlRootElement(name = "piano")
public class Piano {

    @XmlElement(required = true)
    protected Builder builder;
    @XmlElement(required = true)
    protected String model;
    @XmlElement(name = "back-sides", required = true)
    protected String backSides;
    @XmlElement(required = true)
    protected Top top;
    @XmlJavaTypeAdapter(NoteTypeAdapter.class)
    @XmlElement
    protected String notes;
    @XmlAttribute(required = true)
    protected String id;

    /**
     * Gets the value of the builder property.
     * 
     * @return
     *     possible object is
     *     {@link Builder }
     *     
     */
    public Builder getBuilder() {
        return builder;
    }

    /**
     * Sets the value of the builder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Builder }
     *     
     */
    public void setBuilder(Builder value) {
        this.builder = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the backSides property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackSides() {
        return backSides;
    }

    /**
     * Sets the value of the backSides property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackSides(String value) {
        this.backSides = value;
    }

    /**
     * Gets the value of the top property.
     * 
     * @return
     *     possible object is
     *     {@link Top }
     *     
     */
    public Top getTop() {
        return top;
    }

    /**
     * Sets the value of the top property.
     * 
     * @param value
     *     allowed object is
     *     {@link Top }
     *     
     */
    public void setTop(Top value) {
        this.top = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
